#! /usr/bin/env python3
#
# 2019-07-17
# Colton Grainger 

"""
Function definitions for the RDA images script (rdai).
"""

# from "__main__" section of rdai.py {{{ #

# import os.path, sys
# args = get_cli_arguments()

# # directory locations relative to RDAI installation
# rdai_dir = get_rdai_path()
# rdai_schema_dir = os.path.join(rdai_dir, "schema")
# rdai_script_dir = os.path.join(rdai_dir, "script")
# rdai_user_dir = os.path.join(rdai_dir, "user")

# # directory location for outputs
# output_dir = os.path.abspath(args.output_dir)
# debug("output directory: {}".format(output_dir))

# # directory location for data
# data_dir = os.path.abspath(args.data_dir)
# debug("data directory: {}".format(data_dir))

# config = get_config_info(rdai_script_dir, rdai_user_dir)
# plat = get_platform()
#  }}} fold # 

# args component definitions {{{ #

# if args.component == 'metadata':
#     if args.metadata_input in ['csv','json','xml']:
#         # TODO if catalog exists, raise warning and minimally update
#         # TODO unless forcing flag
#         create_catalog(data_dir, output_dir, args.metadata_input)
#     else:
#         raise NotImplementedError('cannot collect metadata from "{}" format'.format(args.metadata_input))

# elif args.component == 'uuid':
#     # TODO if uuid_dict exists, raise warning and minimally update
#     # TODO unless forcing flag
#     create_uuids(data_dir, output_dir)

# elif args.component == 'bundle':
#     # TODO test if uuid_dict and catalog exist
#     merge_uuids_into_catalog(output_dir)
#     # TODO optimize the tail-recursion
#     unnormalize_catalog(output_dir)
#     # TODO avoid frivilous updates with rsync (or shutils?)
#     rename_by_uuids(data_dir, output_dir)

# elif args.component == 'database':
#     # TODO test if bundle exists
#     # TODO unnormalized data as a DataFrame 
#     # TODO read MySQL config
#     # TODO inject (or update?) DataFrame

# else:
#     raise ValueError('the "{}" component is not a valid RDAI option'.format(args.component))
#  }}} #

# fakesection: messaging functions {{{ # 

# These functions were originally part of MathBook XML.
# Adapted from https://github.com/rbeezer/mathbook/tree/dev/script
# Copyright 2010-2016 Robert A. Beezer, released GPLv2

# 2016-05-05: this section should run under Python 2.7 and Python 3

# TODO why are these private functions?
# DONE date
def verbose(msg):
    """Write a message to the console on program progress"""
    try:
        global args
        # None if not set at all
        if args.verbose and args.verbose >= 1:
            print('RDAI: {}'.format(msg))
    except NameError:
        print('RDAI: {}'.format(msg))

def debug(msg):
    """Write a message to the console with some raw information"""
    try:
        global args
        # None if not set at all
        if args.verbose and args.verbose >= 2:
            print('RDAI-DEBUG: {}'.format(msg))
    except NameError:
        print('RDAI-DEBUG: {}'.format(msg))
#  }}} 

# fakesection: operating system functions {{{
# These functions were originally part of MathBook XML.
# Adapted from https://github.com/rbeezer/mathbook/tree/dev/script
# Copyright 2010-2016 Robert A. Beezer, released GPLv2

def get_rdai_path():
    """Returns path of root of RDAI distribution"""
    import sys, os.path
    verbose("discovering RDAI root directory from mbx script location")
    # full path to script itself
    rdai_path = os.path.abspath(sys.argv[0])
    # split "RDAI" executable off path
    script_dir, _ = os.path.split(rdai_path)
    # split "script" path off executable
    distribution_dir, _ = os.path.split(script_dir)
    verbose("RDAI distribution root directory: {}".format(distribution_dir))
    return distribution_dir


def get_source_path(source_file):
    """Returns path to content to be acted upon"""
    import sys, os.path
    verbose("discovering source directory from source location")
    # split path off filename
    source_dir, _ = os.path.split(source_file)
    return os.path.normpath(source_dir)

def get_executable(config, exec_name):
    "Queries configuration file for executable name, verifies existence in Unix"
    import os
    import platform
    import subprocess

    # http://stackoverflow.com/questions/11210104/check-if-a-program-exists-from-a-python-script
    # suggests  where.exe  as Windows equivalent (post Windows Server 2003)
    # which  = 'where.exe' if platform.system() == 'Windows' else 'which'

    # get the name, but then see if it really, really works
    debug('locating "{}" in [executables] section of configuration file'.format(exec_name))
    config_name = config.get('executables', exec_name)

    devnull = open(os.devnull, 'w')
    try:
        result_code = subprocess.call(['which', config_name], stdout=devnull, stderr=subprocess.STDOUT)
    except OSError:
        print('RDAI:WARNING: executable existence-checking was not performed (e.g. on Windows)')
        result_code = 0  # perhaps a lie on Windows
    if result_code != 0:
        error_message = '\n'.join([
                        'cannot locate executable with configuration name "{}" as command "{}"',
                        'Edit the configuration file and/or install the necessary program'])
        raise OSError(error_message.format(exec_name, config_name))
    debug("{} executable: {}".format(exec_name, config_name))
    return config_name

def get_cli_arguments():
    """Return the CLI arguments in parser object"""
    import argparse
    parser = argparse.ArgumentParser(description='RDAI utility script', formatter_class=argparse.RawTextHelpFormatter)

    verbose_help = '\n'.join(["verbosity of information on progress of the program",
                              "  -v  is actions being performed",
                              "  -vv is some additional raw debugging information"])
    parser.add_argument('-v', '--verbose', help=verbose_help, action="count")

    component_info = [
        ('metadata', 'Metadata for data files.'),
        ('uuid', 'UUIDs for data files.'),
        ('bundle', 'Bundle from metadata, UUIDs, and data files.'),
        ('database', 'Database from bundle.'),
    ]
    component_help = 'Possible components are:\n' + '\n'.join(['  {} - {}'.format(info[0], info[1]) for info in component_info])
    parser.add_argument('-c', '--component', help=component_help, action="store", dest="component")

    metadata_input_info = [
        ('csv', 'Recursively read *.csv files in data directory. Format: "key","value".'),
        ('json', 'Recursively read *.json files in data directory. Format: {"key":"value"}.'),
        ('xml', 'Read single *.xml file from root of data directory. See docs for XML Schema.'),
    ]
    metadata_input_help = 'Possible metadata input formats are:\n' + '\n'.join(['  {} - {}'.format(info[0], info[1]) for info in metadata_input_info])
    parser.add_argument('-m', '--metadata-input', help=metadata_input_help, action="store", dest='metadata_input')

    parser.add_argument('-d', '--data-dir', help='path to data directory', action="store", dest='data_dir')
    parser.add_argument('-o', '--output-dir', help='path to output directory', action="store", dest='output_dir')
    return parser.parse_args()

    # "nargs" allows multiple options following the flag
    # separate by spaces, can't use "-stringparam"
    # stringparams is a list of strings on return
    # parser.add_argument('-p', '--parameters', nargs='+', help='stringparam options to pass to XSLT extraction stylesheet (option/value pairs)',
    #                      action="store", dest='stringparams')
    # # default to an empty string, which signals root to XSL stylesheet
    # parser.add_argument('-r', '--restrict', help='restrict to subtree rooted at element with specified xml:id',
    #                      action="store", dest='xmlid', default='')
    # parser.add_argument('-s', '--server', help='base URL for server (webwork only)', action="store", dest='server')

def sanitize_directory(dir):
    """Verify directory name, or raise error"""
    # Use with os.path.join, and do not sweat separator
    import os.path
    verbose('verifying directory: {}'.format(dir))
    if not(os.path.isdir(dir)):
        raise ValueError('directory {} does not exist'.format(dir))
    return dir

# Certificate checking is buggy, exception raised is malformed
# 2015/10/07 Turned off verification in three places
# Command line warning can be disabled, requests.packages.urllib3.disable_warnings()
def sanitize_url(url):
    """Verify a server address, append a slash"""
    verbose('validating, cleaning server URL: {}'.format(url))
    import requests
    try:
        requests.get(url, verify=False)
    except requests.exceptions.RequestException as e:
        root_cause = str(e)
        msg = "There was a problem with the server URL, {}\n".format(url)
        raise ValueError(msg + root_cause)
    # We expect relative paths to locations on the server
    # So we add a slash if there is not one already
    if url[-1] != "/":
        url = url + "/"
    return url

def sanitize_alpha_num_underscore(param):
    """Verify parameter is a string containing only alphanumeric and undescores"""
    import string
    allowed = set(string.ascii_letters + string.digits + '_')
    verbose('verifying parameter: {}'.format(param))
    if not(set(param) <= allowed):
        raise ValueError('param {} contains characters other than a-zA-Z0-9_ '.format(param))
    return param

def get_config_info(script_dir, user_dir):
    """Return configuation in object for querying"""
    import sys,os.path
    config_filename = "rdai.cfg"
    default_config_file = os.path.join(script_dir, config_filename)
    user_config_file = os.path.join(user_dir, config_filename)
    config_file_list = [default_config_file, user_config_file]
    # ConfigParser was renamed to configparser in Python 3
    try:
        import configparser
    except ImportError:
        import ConfigParser as configparser
    config = configparser.SafeConfigParser()
    verbose("parsing configuration files: {}".format(config_file_list))
    files_read = config.read(config_file_list)
    debug("configuration files used/read: {}".format(files_read))
    if not(user_config_file in files_read):
        msg = "using default configuration only, custom configuration file not used at {}"
        verbose(msg.format(user_config_file))
    return config

def copy_data_directory(source_file, data_dir, tmp_dir):
    """Stage directory from CLI argument into the working directory"""
    import os.path, shutil
    verbose("formulating data directory location")
    source_full_path, _ = os.path.split(os.path.abspath(source_file))
    data_full_path = sanitize_directory(os.path.join(source_full_path, data_dir))
    data_last_step = os.path.basename(os.path.normpath(data_full_path))
    destination_root = os.path.join(tmp_dir, data_last_step)
    debug("copying data directory {} to working location {}".format(data_full_path, destination_root))
    shutil.copytree(data_full_path, destination_root)

def get_platform():
    """Return a string that tells us whether we are on Windows."""
    import platform
    return platform.system()

def is_os_64bit():
    """Return true if we are running a 64-bit OS.
    http://stackoverflow.com/questions/2208828/detect-64-bit-os-windows-in-python"""
    import platform
    return platform.machine().endswith('64')

def break_windows_path(python_style_dir):
    """Replace python os.sep with msys-acceptable "/" """
    import re
    return re.sub(r"\\", "/", python_style_dir)

# }}}

# fakesection: metadata functions {{{
# e.g., $ rdai -c metadata -m csv -d ~/data -o ~/tmp

# TODO def create_catalog(data_dir, output_dir, args.metadata_input):

def get_normalized_catalog(data_dir):
    """Catalogs the files and directories below the data_dir (relative path),
    given '.csv' or '.tsv' metadata (TODO or '.json') in the directory tree.

    :pool_metadata: "metadata gathering" function defined below.

    :data_dir: Relative path to directory to be cataloged. Should be a directory.
    :returns: Nested json describing files, directories, and metadata.

    """
    from pathlib import Path
    import os
    import magic
    import csv

    # Initialize dictionary.
    normalized_catalog = {} 
    # Suppose data_dir is a parent.
    parent = Path(data_dir)

    if parent.is_dir():
        # List relative paths to children.
        children = [os.path.join(parent, x) for x in os.listdir(parent)]
        # Recurse down by calling `get_normalized_catalog` for each child.
        normalized_catalog['contents'] = [get_normalized_catalog(child) for child in children]
        # WARNING. We reserve the key 'contents' for inclusion of lists of child
        # dictionaries. Whence, the key 'contents' should appear 0 or 1 times in
        # each child dictionary.

        # Determine if `child` is a metadata tag file, and if so, in which input format.
        for child in children:
            _, ext = os.path.splitext(child)
            # TODO Test for xml and json.
            if ext in ['.csv', '.tsv']:
                # Update `normalized_catalog` with metadata from child.
                normalized_catalog = pool_metadata(child, normalized_catalog)

    # If the parent is not a directory, write out file-level metadata.
    # This is the floor of the recursive function call.
    else:
        normalized_catalog['file_path'] = str(parent)
        normalized_catalog['media_type'] = magic.from_file(str(parent), mime=True)
        # Eventually I'd like to restructure the program to recurse on
        # filetypes, so as to avoid reading headers redunandtly. At that
        # point, python-magic might not need to test for the file media_type. 2019-07-27

    return normalized_catalog

def pool_metadata(tagfile, normalized_catalog):
    """Collects key-value pairs from a given metadata tag file (here '.csv' or '.tsv'),
    then updates a given normalized catalog. TODO Add args for json or xml.

    :tagfile: Relative path to metadata file.
    :normalized_catalog: Dictionary to write out key-value pairs.
    :returns: Updated content dictionary.

    """
    import csv
    # Initial state.
    to_parse = False 

    # Test the well-formedness of key/value pairs in the tagfile.
    try:
        with open(tagfile, newline='') as file:

            # Read head of CSV file and determine dialect.
            try:
                dialect = csv.Sniffer().sniff(file.read(2048), delimiters=',\t')
                # If we can parse the header, then toggle to_parse and read the rest.
                to_parse = True
            except csv.Error as e:
                verbose('CSV Sniffer failed to parse file: {}, error: {}'.format(tagfile, e))

            if to_parse:
                file.seek(0)
                reader = csv.reader(file, dialect)
                # Read the tagfile (for the first two fields from each non-empty row).
                key_value_pairs = {
                        rows[0].strip():rows[1].strip()
                        for rows in reader if any(rows)}
                        # To concatenate all rows 2+, try. <ccg, 2019-07-27> 
                        # rows[0].strip():[x.strip for x in rows[1:]]
                # Add key_value_pairs to the current level of the
                # normalized_catalog dictionary.
                normalized_catalog = {
                        **normalized_catalog,
                        **key_value_pairs}

    # Message for key/value error.
    except csv.Error as e:
        verbose('Syntax error: key-value pair in file: {}, line {}: {}'.format(
            tagfile, reader.line_num, e))

    # Return normalized_catalog updated with key/value pairs from tagfile.
    return normalized_catalog
i
# }}}

# fakesection: uuid functions {{{
# abstracted from 2019-06-15-assign-uuids.py
# Desired CLI use. $ rdai -c uuid -d ~/data -o ~/tmp

def get_fixed_seq():
    """Declares/updates global fixed_seq, which seeds mind_uuid()."""
    global fixed_seq
    from random import getrandbits
    fixed_seq = getrandbits(14)

def mint_uuid(node=None):
    """Returns a semi-sequential uuid. Requires global fixed_seq to have been
    defined as a seed."""
    import time
    from uuid import uuid1, getnode
    # answered 2019-05-16T13:46 by imposeren, CC-3.0
    # <https://stackoverflow.com/questions/56119272>

    # get_fixed_seq() should be called prior to mint_uuid().
    global fixed_seq

    # Returns a 32-character hexadecimal string, which can be
    # stored in MySQL as BINARY(16) for efficient indexing. C.f.,
    # <https://mysqlserverteam.com/storing-uuid-values-in-mysql-tables/>
    return uuid1(node=node, clock_seq=fixed_seq).hex

def assign_uuid(filepath, overwrite=False):
    """Reads EXIF:ImageUniqueID tag for valid uuid. If no uuid exists, write
    mind_uuid() to EXIF:ImageUniqueID tag."""
    import exiftool
    with exiftool.ExifTool() as et:
        # By default, if the `EXIF:ImageUniqueID` tag is empty, uuid is assigned
        # to None.
        uuid = et.get_tag('ImageUniqueID', filepath)

        # If a uuid exists and overwrite is False, do nothing.
        if uuid != None and not overwrite:
            verbose("Tag EXIF:ImageUniqueID={} already exists in file {}.".format(uuid, filepath))

        # Else, no uuid was read by exiftool, or overwrite has been set to True.
        else:
            uuid = mint_uuid()
            et.execute_json('-ImageUniqueID={}'.format(uuid).encode(), filepath.encode())
            verbose("Wrote tag EXIF:ImageUniqueID={} to file {}.".format(uuid, filepath))

    # Pass either the read uuid from exiftool or the assigned from mint_uuid().
    return uuid

def get_files_under(data_dir):
    """Returns an iterator of posix paths to each file under data_dir. Is not sorted.

    :dir_path: Relative path to supposed directory.
    """

    from pathlib import Path
    for p in sorted(Path(data_dir).glob('**/*')):
        if p.is_file():
            yield p

def generate_uuids_under(data_dir):
    # TODO configuration file for assignment rules?
    """Creates a dictionary whose keys are paths relative to `scripts`
    and whose values are tuples of semi-sequentially assigned UUIDs.

    :data_dir: Relative path to data (image) files.
    :returns: Dictionary of UUIDs (assigned calling sequential_uuid()) and file extensions?

    """
    assignments = []
    for page in get_files_under(data_dir):
        page_ext = os.path.splitext(page)[1]
        assignments.extend((page, (sequential_uuid(), page_ext)))
    return assignments

# {sequential_uuid().hex : [str(image), magic.from_file(str(image), mime=True), os.path.getsize(str(image))] for image in find_images(os.path.join(git_repo_abs_dir(), "stage"))}
# DataFrame.from_dict(d, orient='index', columns=['file_path', 'mime_type', 'file_size'])
# df[df.mime_type.str.startswith("image")]

# }}}

# fakesection: bundle functions {{{
# e.g., $ rdai -c bundle -d ~/data -o ~/tmp

# to unnormalize the json catalog in the output_dir ~/tmp
# TODO optimize recursive step <ccg, 2019-07-17> # 
# def unnormalize_catalog(output_dir):

# to bundle the existing uuid_dict and catalog
# def merge_uuids_into_catalog(output_dir):

# to rsync cataloged files from ~/data to ~/tmp and rename by uuid
# TODO avoid frivilous updates with rsync (or shutils?)
# TODO add configuration for remote output_dir <ccg, 2019-07-17> # 
# def rename_by_uuids(data_dir, output_dir):

# }}}

# fakesection: database functions {{{
# e.g., $ rdai -c database -o ~/tmp
# to retrieve the database config and handle errors
# to initialize a test database with the rdai schema
# to inject bundled metadata into the test database
# 2019-06-25-create-sql-engine.py

# }}}

# fakesection: NARA functions {{{ # 
# 2019-06-01-sample-downloads.py
#  1}}} # 
